(function(){
'use strict';
const E=window.__YEnh={};
function getMentions(text){return [...new Set((String(text||'').match(/@[A-Za-z0-9_]{3,30}/g)||[]).map(x=>x.slice(1).toLowerCase())]}
async function mentionUsers(text){const names=getMentions(text);if(!names.length)return[];const {data,error}=await db.from('profiles').select('id,username,display_name').in('username',names);return error?[]:(data||[])}
async function addMentions(type,id,text){const users=await mentionUsers(text);let added=0,skipped=0;for(const u of users){const q=await db.rpc('yw_can_be_mentioned',{target_user:u.id,actor_user:me.id});if(q.error||q.data!==true){skipped++;continue}const r=await db.from('content_mentions').insert({content_type:type,content_id:id,mentioned_user_id:u.id,mentioned_by:me.id});if(r.error)skipped++;else added++}return{added,skipped}}
async function enhancedCreatePost(){try{const body=$('#body')?.value.trim()||'',f=$('#photo')?.files?.[0];if(!body&&!f)return toast('Write something or add a photo');const image=await upload(f,'posts');const r=await db.from('posts').insert({user_id:me.id,body:body||'',image_url:image,visibility:$('#pv')?.value||'public',engagement_visibility:$('#ev')?.value||'public',allow_download:$('#dl')?.checked!==false}).select('id').single();if(r.error)throw r.error;const m=await addMentions('post',r.data.id,body);toast(m.skipped?'Post published; some mentions were not allowed':'Post published');route('home')}catch(e){toast(e.message)}}
function storyEditor(file,source){const old=document.getElementById('modal');old.innerHTML='<div class="modal"><div class="card modalbox"><div class="row"><h2 class="grow">Add to Story</h2><button class="icon" id="yx">×</button></div><p class="muted tiny">Mention people with @username. Their notification respects their mention privacy.</p><textarea id="ystorycaption" class="field" style="min-height:110px" placeholder="Add a caption or @mention..."></textarea><div class="row" style="margin-top:10px"><select id="ystoryvis" class="select"><option value="public">Public</option><option value="followers">Followers</option><option value="close_friends">Close Friends</option></select><label class="btn"><input id="ystorydl" type="checkbox" checked> Allow download</label></div><button class="btn primary" id="ystorygo" style="width:100%;margin-top:12px">Share to Story</button></div></div>';
$('#yx').onclick=()=>old.innerHTML='';$('#ystorygo').onclick=async()=>{try{let media=null,mt='image';if(file){media=await upload(file,'stories');mt=file.type.startsWith('video/')?'video':'image'}if(source?.media_url){media=source.media_url;mt=source.media_type||'image'}if(!media)return toast('No story media selected');const caption=$('#ystorycaption').value.trim();const row={user_id:me.id,media_url:media,media_type:mt,caption,expires_at:new Date(Date.now()+86400000).toISOString(),visibility:$('#ystoryvis').value,engagement_visibility:'private',allow_download:$('#ystorydl').checked,source_type:source?.type||null,source_post_id:source?.type==='post'?source.id:null,source_reel_id:source?.type==='reel'?source.id:null};const r=await db.from('stories').insert(row).select('id').single();if(r.error)throw r.error;const m=await addMentions('story',r.data.id,caption);toast(m.skipped?'Story shared; some mentions were not allowed':'Story shared');old.innerHTML=''}catch(e){toast(e.message)}}}
async function reshareToStory(type,id){try{let row,source;if(type==='post'){const r=await db.from('posts').select('id,user_id,body,image_url,created_at').eq('id',id).maybeSingle();row=r.data;if(!row)throw Error('Post unavailable');source={type:'post',id:row.id,media_url:row.image_url,media_type:'image',body:row.body}}else{const r=await db.from('reels').select('id,user_id,media_url,caption').eq('id',id).maybeSingle();row=r.data;if(!row)throw Error('Reel unavailable');source={type:'reel',id:row.id,media_url:row.media_url,media_type:row.media_url?.match(/\.(mp4|webm|mov)(\?|$)/i)?'video':'image',body:row.caption}}const can=await db.rpc('yw_can_reshare',{owner_user:row.user_id,actor_user:me.id});if(can.error||can.data!==true)throw Error('This creator does not allow this content to be added to stories');if(!source.media_url){const safe=String(source.body||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\n/g,'<br>');const svg='<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1920"><rect width="100%" height="100%" fill="#111526"/><foreignObject x="70" y="350" width="940" height="1200"><div xmlns="http://www.w3.org/1999/xhtml" style="font:700 58px system-ui;color:white;line-height:1.3;word-wrap:break-word">'+safe+'</div></foreignObject></svg>';const file=new File([svg],'post-story.svg',{type:'image/svg+xml'});return storyEditor(file,source)}storyEditor(null,source)}catch(e){toast(e.message)}}
async function interceptReelUpload(e){const input=e.target.closest('#rf');if(!input)return;e.preventDefault();e.stopImmediatePropagation();const f=input.files?.[0];if(!f)return;try{const caption=prompt('Reel caption (use @username to mention someone):','')||'';const u=await upload(f,'reels');const r=await db.from('reels').insert({user_id:me.id,media_url:u,caption,visibility:'public',engagement_visibility:'public',allow_download:true}).select('id').single();if(r.error)throw r.error;const m=await addMentions('reel',r.data.id,caption);toast(m.skipped?'Reel uploaded; some mentions were not allowed':'Reel uploaded');route('reels')}catch(err){toast(err.message)}}
function interceptPost(e){const b=e.target.closest('#post');if(!b)return;e.preventDefault();e.stopImmediatePropagation();enhancedCreatePost()}
function interceptReelShare(e){const b=e.target.closest('[data-share-reel]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();reshareToStory('reel',b.dataset.shareReel)}
function interceptPostShare(e){const b=e.target.closest('[data-share]');if(!b)return;e.preventDefault();e.stopImmediatePropagation();const id=b.dataset.share,m=document.getElementById('modal');m.innerHTML='<div class="modal"><div class="card modalbox"><div class="row"><h2 class="grow">Share</h2><button class="icon" id="sx">×</button></div><button class="btn primary" id="addstory" style="width:100%">Add post to your story</button><button class="btn" id="copyshare" style="width:100%;margin-top:8px">Copy post link</button></div></div>';$('#sx').onclick=()=>m.innerHTML='';$('#addstory').onclick=()=>reshareToStory('post',id);$('#copyshare').onclick=()=>{const u=location.href.split('#')[0]+'#post-'+id;navigator.clipboard?.writeText(u).then(()=>toast('Link copied'))}}
function interceptStoryFile(e){const input=e.target.closest('#sf');if(!input)return;e.preventDefault();e.stopImmediatePropagation();const f=input.files?.[0];if(f)storyEditor(f,null)}
function enhanceSettings(){const page=document.getElementById('page');if(!page||page.querySelector('#yprivacy'))return;const heading=page.querySelector('h2');if(!heading||!/(settings|सेटिंग)/i.test(heading.textContent||''))return;const box=page.querySelector('.sidecard');if(!box)return;const el=document.createElement('div');el.id='yprivacy';el.className='latest';el.innerHTML='<b>Mention & Story Privacy</b><div class="tiny muted" style="margin:6px 0 12px">Control who can mention you and who can add your posts/reels to their stories.</div><div class="setting"><div><b>Who can mention me?</b></div><select id="ymprivacy" class="select" style="width:auto"><option value="everyone">Everyone</option><option value="followers">People I follow</option><option value="nobody">Nobody</option></select></div><div class="setting"><div><b>Who can add my posts/reels to stories?</b></div><select id="yrprivacy" class="select" style="width:auto"><option value="everyone">Everyone</option><option value="followers">People I follow</option><option value="nobody">Nobody</option></select></div><div class="tiny muted" id="ypsave" style="margin-top:10px">Saving automatically.</div>';box.insertBefore(el,box.querySelector('.latest')||box.firstChild);db.from('user_settings').select('mention_privacy,reshare_privacy').eq('user_id',me.id).maybeSingle().then(({data})=>{if(data){$('#ymprivacy').value=data.mention_privacy||'everyone';$('#yrprivacy').value=data.reshare_privacy||'everyone'}});const save=async()=>{const r=await db.from('user_settings').upsert({user_id:me.id,mention_privacy:$('#ymprivacy').value,reshare_privacy:$('#yrprivacy').value},{onConflict:'user_id'});$('#ypsave').textContent=r.error?'Could not save: '+r.error.message:'Saved'};$('#ymprivacy').onchange=save;$('#yrprivacy').onchange=save}

/* Auth enhancement: email OTP + phone OTP + Google/Facebook entry points.  OAuth buttons are only usable after their provider credentials are enabled in Supabase. */
function authOverlay(){
  if(!window.db||!window.me)return;
  const root=document.body;
  const email=root.querySelector('input[type="email"]');
  if(!email||root.querySelector('#yauthMethods'))return;
  const password=root.querySelector('input[type="password"]');
  const host=password?.parentElement||email.parentElement;
  if(!host)return;
  const box=document.createElement('div');box.id='yauthMethods';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid var(--line,#2b3047)';
  box.innerHTML='<div style="font-size:12px;color:#a7acc1;margin-bottom:9px">More secure sign-in options</div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px"><button type="button" class="btn" id="yEmailOtp">Email OTP</button><button type="button" class="btn" id="yPhoneOtp">Phone OTP</button><button type="button" class="btn" id="yGoogle">Continue with Google</button><button type="button" class="btn" id="yFacebook">Continue with Facebook</button></div><div id="yAuthStatus" class="tiny muted" style="margin-top:9px"></div>';
  host.appendChild(box);
  const status=x=>{const n=document.getElementById('yAuthStatus');if(n)n.textContent=x};
  async function otpPrompt(kind){
    const value=kind==='phone'?prompt('Enter your mobile number with country code, e.g. +919876543210'):email.value.trim();
    if(!value)return;
    status('Sending OTP…');
    const r=kind==='phone'?await db.auth.signInWithOtp({phone:value,options:{shouldCreateUser:true}}):await db.auth.signInWithOtp({email:value,options:{shouldCreateUser:true,emailRedirectTo:location.origin}});
    if(r.error){status(r.error.message);return toast(r.error.message)}
    const code=prompt('OTP sent. Enter the code:');if(!code)return;
    const v=kind==='phone'?await db.auth.verifyOtp({phone:value,token:code,type:'sms'}):await db.auth.verifyOtp({email:value,token:code,type:'email'});
    if(v.error){status(v.error.message);return toast(v.error.message)}
    status('Verified. Loading YOCEWOR…');if(typeof boot==='function')boot();
  }
  $('#yEmailOtp').onclick=()=>otpPrompt('email');$('#yPhoneOtp').onclick=()=>otpPrompt('phone');
  $('#yGoogle').onclick=async()=>{const r=await db.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.href}});if(r.error)toast(r.error.message)};
  $('#yFacebook').onclick=async()=>{const r=await db.auth.signInWithOAuth({provider:'facebook',options:{redirectTo:location.href}});if(r.error)toast(r.error.message)};
}
new MutationObserver(()=>{try{enhanceSettings();authOverlay()}catch(e){}}).observe(document.body,{childList:true,subtree:true});
document.addEventListener('click',interceptPost,true);document.addEventListener('click',interceptPostShare,true);document.addEventListener('click',interceptReelShare,true);document.addEventListener('change',interceptReelUpload,true);document.addEventListener('change',interceptStoryFile,true);setTimeout(enhanceSettings,700);setTimeout(authOverlay,900);E.ready=true;
})();
