(function(){'use strict';
  const SUPA_URL='https://mzntgjyecymcpzciklfk.supabase.co',SUPA_KEY='sb_publishable_AAXGC4EmiD4ELszpchz9Dw_Eryr6Usn';
  let client=null;try{if(window.supabase?.createClient)client=window.supabase.createClient(SUPA_URL,SUPA_KEY)}catch(e){console.error(e)}
  function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function hideSplash(){const s=document.getElementById('splash');if(s){s.classList.add('hide');setTimeout(()=>s.remove(),500)}}
  function showAuth(){
    const root=document.getElementById('root');if(!root||root.children.length)return;
    root.innerHTML='<section style="min-height:calc(100vh - 70px);display:grid;place-items:center;padding:18px;background:radial-gradient(circle at 20% 0,#291046,transparent 35%),#07040f;color:#fff;font-family:system-ui,sans-serif"><div style="width:min(520px,100%);background:#111526;border:1px solid #2b3047;border-radius:22px;padding:22px;box-shadow:0 18px 55px #0007"><h1 style="margin:0 0 6px">Welcome to <span style="background:linear-gradient(90deg,#ff6a00,#ff2f7e,#7c4dff);-webkit-background-clip:text;color:transparent">YOCEWOR</span></h1><p style="color:#a7acc1">Your Voice. Your World.</p><div style="display:flex;gap:8px;margin:18px 0"><button id="fsLoginTab" style="flex:1;padding:11px;border:0;border-radius:12px;background:linear-gradient(100deg,#ff6a00,#ff2f7e);color:#fff;font-weight:800">Login</button><button id="fsSignupTab" style="flex:1;padding:11px;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff;font-weight:800">Create account</button></div><div id="fsForm"></div></div></section>';
    const form=document.getElementById('fsForm');
    function render(mode){form.innerHTML=mode==='login'?'<input id="fsEmail" type="email" placeholder="Email" style="width:100%;padding:12px;box-sizing:border-box;margin:5px 0;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff"><input id="fsPass" type="password" placeholder="Password" style="width:100%;padding:12px;box-sizing:border-box;margin:5px 0;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff"><button id="fsGo" style="width:100%;margin-top:8px;padding:12px;border:0;border-radius:12px;background:linear-gradient(100deg,#ff6a00,#ff2f7e);color:#fff;font-weight:800">Login</button><button id="fsOtp" style="width:100%;margin-top:8px;padding:12px;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff;font-weight:800">Login with Email OTP</button><div id="fsMsg" style="color:#a7acc1;font-size:13px;margin-top:10px"></div>':'<input id="fsName" placeholder="Full name" style="width:100%;padding:12px;box-sizing:border-box;margin:5px 0;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff"><input id="fsUser" placeholder="Username" style="width:100%;padding:12px;box-sizing:border-box;margin:5px 0;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff"><input id="fsEmail" type="email" placeholder="Email" style="width:100%;padding:12px;box-sizing:border-box;margin:5px 0;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff"><input id="fsPass" type="password" placeholder="Password" style="width:100%;padding:12px;box-sizing:border-box;margin:5px 0;border:1px solid #2b3047;border-radius:12px;background:#151a2b;color:#fff"><button id="fsGo" style="width:100%;margin-top:8px;padding:12px;border:0;border-radius:12px;background:linear-gradient(100deg,#ff6a00,#ff2f7e);color:#fff;font-weight:800">Create account</button><div id="fsMsg" style="color:#a7acc1;font-size:13px;margin-top:10px"></div>';
      document.getElementById('fsGo').onclick=async function(){try{if(!client)return msg('Authentication service is not ready. Please reload.');const email=document.getElementById('fsEmail').value.trim().toLowerCase(),pass=document.getElementById('fsPass').value;if(mode==='login'){const r=await client.auth.signInWithPassword({email,password:pass});if(r.error)throw r.error;location.reload()}else{const u=document.getElementById('fsUser').value.trim().toLowerCase();if(!/^[a-z0-9_]{3,30}$/.test(u))return msg('Username must be 3–30 letters, numbers or _.');const r=await client.auth.signUp({email,password:pass,options:{data:{username:u,display_name:document.getElementById('fsName').value.trim()||u}}});if(r.error)throw r.error;msg(r.data.session?'Account created. Loading…':'Account created. Check your email for verification.')}}catch(e){msg(e.message)}};
      document.getElementById('fsOtp')?.addEventListener('click',async function(){try{if(!client)return msg('Authentication service is not ready.');const email=document.getElementById('fsEmail').value.trim().toLowerCase();if(!email)return msg('Enter your email first.');const r=await client.auth.signInWithOtp({email,options:{shouldCreateUser:false}});if(r.error)throw r.error;const code=prompt('OTP sent to your email. Enter the OTP:');if(!code)return;const v=await client.auth.verifyOtp({email,token:code,type:'email'});if(v.error)throw v.error;location.reload()}catch(e){msg(e.message)}});
    }
    function msg(x){const n=document.getElementById('fsMsg');if(n)n.textContent=x}
    document.getElementById('fsLoginTab').onclick=()=>render('login');document.getElementById('fsSignupTab').onclick=()=>render('signup');render('login');
  }
  setTimeout(function(){hideSplash();const root=document.getElementById('root');if(root&&root.children.length===0)showAuth();else if(typeof window.boot==='function'){try{window.boot()}catch(e){console.error(e)} }},3200);
})();
