(()=>{
if(!document.querySelector('link[rel="icon"]')){const l=document.createElement('link');l.rel='icon';l.href='favicon.svg';document.head.appendChild(l)}
const esc2=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const oldRoute=window.route;
async function storiesPage(){
 const r=await db.from('stories').select('*').gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}).limit(50);
 const rows=r.data||[]; const ids=[...new Set(rows.map(x=>x.user_id))],mp={};
 if(ids.length){const q=await db.from('profiles').select('*').in('id',ids);(q.data||[]).forEach(p=>mp[p.id]=p)}
 return `<div class="card pad"><div class="row"><div class="grow"><h2 style="margin:0">Stories</h2><div class="tiny muted">Photos and moments disappear after 24 hours.</div></div><label class="btn primary file">＋ Add story<input id="storyFile" type="file" accept="image/*,video/*"></label></div><div style="margin-top:16px;display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:10px">${rows.map(s=>`<button class="card" style="padding:0;overflow:hidden;text-align:left;color:inherit" data-story="${s.id}">${s.media_type==='video'?`<video src="${esc2(s.media_url)}" muted style="width:100%;height:210px;object-fit:cover"></video>`:`<img src="${esc2(s.media_url)}" style="width:100%;height:210px;object-fit:cover">`}<div style="padding:9px"><b>${esc2(mp[s.user_id]?.display_name||'User')}</b><div class="tiny muted">${esc2(s.caption||'')}</div></div></button>`).join('')||'<div class="empty">No active stories. Add yours.</div>'}</div></div>`;
}
async function uploadStory(file){try{if(!file)return;const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,'');const path=`${me.id}/stories/${Date.now()}-${safe}`;if(file.size>12*1024*1024)throw Error('Story must be under 12MB');const u=await db.storage.from('yocewor-media').upload(path,file,{upsert:false,cacheControl:'3600'});if(u.error)throw u.error;const url=db.storage.from('yocewor-media').getPublicUrl(path).data.publicUrl;const type=file.type.startsWith('video/')?'video':'image';const q=await db.from('stories').insert({user_id:me.id,media_url:url,media_type:type,caption:''});if(q.error)throw q.error;toast('Story added');oldRoute('stories')}catch(e){toast(e.message)}}
async function storyOpen(id){const r=await db.from('stories').select('*').eq('id',id).maybeSingle();if(!r.data)return;const s=r.data;await db.from('story_views').upsert({story_id:id,viewer_id:me.id},{onConflict:'story_id,viewer_id'}).catch(()=>{});$('#modal').innerHTML=`<div class="modal"><div class="card modalbox" style="background:#05070c;text-align:center"><button class="icon" id="sx" style="float:right">×</button>${s.media_type==='video'?`<video src="${esc2(s.media_url)}" controls autoplay playsinline style="width:100%;max-height:70vh"></video>`:`<img src="${esc2(s.media_url)}" style="width:100%;max-height:70vh;object-fit:contain">`}<div style="padding:12px">${esc2(s.caption||'')}</div></div></div>`;$('#sx').onclick=()=>$('#modal').innerHTML=''}
async function profileEditor(){const p=meP||{};$('#modal').innerHTML=`<div class="modal"><div class="card modalbox"><div class="row"><b class="grow">Edit profile</b><button class="icon" id="px">×</button></div><label>Name</label><input id="epName" class="field" value="${esc2(p.display_name)}"><label>Username</label><input id="epUser" class="field" value="${esc2(p.username)}"><label>Bio</label><textarea id="epBio" class="field" style="min-height:120px">${esc2(p.bio||'')}</textarea><button class="btn primary" id="saveProfile">Save profile</button></div></div>`;$('#px').onclick=()=>$('#modal').innerHTML='';$('#saveProfile').onclick=async()=>{const q=await db.from('profiles').update({display_name:$('#epName').value.trim()||p.display_name,username:$('#epUser').value.trim().toLowerCase(),bio:$('#epBio').value.trim(),updated_at:new Date().toISOString()}).eq('id',me.id);if(q.error)toast(q.error.message);else{meP=await profile(me.id);$('#modal').innerHTML='';toast('Profile updated');oldRoute('profile')}}}
async function newChat(){const u=prompt('Enter the username to message');if(!u)return;const q=await db.from('profiles').select('id,username').eq('username',u.trim().toLowerCase()).maybeSingle();if(!q.data)return toast('User not found');if(q.data.id===me.id)return toast('Choose another user');const mine=await db.from('conversation_members').select('conversation_id').eq('user_id',me.id);const ids=(mine.data||[]).map(x=>x.conversation_id);let cid=null;if(ids.length){const q2=await db.from('conversation_members').select('conversation_id').in('conversation_id',ids).eq('user_id',q.data.id).maybeSingle();cid=q2.data?.conversation_id||null}if(!cid){const c=await db.from('conversations').insert({}).select('id').single();if(c.error)return toast(c.error.message);cid=c.data.id;const m=await db.from('conversation_members').insert([{conversation_id:cid,user_id:me.id},{conversation_id:cid,user_id:q.data.id}]);if(m.error)return toast(m.error.message)}openChat(cid)}
window.route=async v=>{if(v==='stories'){view='stories';bottom();$('#page').innerHTML=await storiesPage();$('#storyFile')?.addEventListener('change',e=>uploadStory(e.target.files[0]));document.querySelectorAll('[data-story]').forEach(x=>x.onclick=()=>storyOpen(x.dataset.story));return}return oldRoute(v)};
const inject=()=>{if(!document.querySelector('[data-view="stories"]')){const b=document.createElement('button');b.className='nav';b.dataset.view='stories';b.innerHTML='<b>◉</b><span>Stories</span>';document.querySelector('.side')?.appendChild(b)}document.querySelectorAll('[data-view="stories"]').forEach(x=>x.onclick=()=>route('stories'));const edit=document.querySelector('#editProfile');if(edit)edit.onclick=profileEditor;const nc=document.querySelector('#newChat');if(nc)nc.onclick=newChat};
new MutationObserver(inject).observe(document.body,{childList:true,subtree:true});inject();
})();