/* YOCEWOR HOME LIVE — stable compact renderer */
(function(){
'use strict';
const U='https://mzntgjyecymcpzciklfk.supabase.co';
const K='sb_publishable_AAXGC4EmiD4ELszpchz9Dw_Eryr6Usn';
const F='id,title,type,last_date,vacancies,apply_url,published,updated_at,created_at';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=d=>{if(!d)return'—';const a=String(d).split('-');return a.length===3?`${a[2]}-${a[1]}-${a[0]}`:esc(d)};
const isAnswer=j=>String(j.type||'').toLowerCase().replace(/[-\s]/g,'_')==='answer_key';
const icons={
 wa:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .3 5.3.3 11.8c0 2.1.5 4.1 1.6 5.9L.2 24l6.5-1.7a11.8 11.8 0 0 0 5.4 1.3h.1c6.5 0 11.8-5.3 11.8-11.8 0-3.1-1.2-6.1-3.5-8.3Z"/></svg>',
 tg:'<svg viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M21.9 3.1 18.6 20c-.3 1.2-1 1.5-2 .9l-5.6-4.1-2.7 2.6c-.3.3-.5.5-1 .5l.4-5.7 10.3-9.3c.4-.4-.1-.6-.6-.2L4.7 12.9.1 11.5c-1-.3-1-1 .2-1.5L20.4 2.2c.9-.3 1.7.2 1.5.9Z"/></svg>',
 ig:'<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="12" cy="12" r="4.2" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="17.4" cy="6.7" r="1.2" fill="currentColor"/></svg>'
};
function job(j){
 const detail='job-details.html?id='+encodeURIComponent(j.id||'');
 const apply=j.apply_url?'<a class="btn green home-apply" href="'+esc(j.apply_url)+'" target="_blank" rel="noopener">Apply</a>':'';
 return '<article class="item home-job"><div class="item-main"><div class="item-title">'+esc(j.title||'Government Recruitment')+' <span class="new">LIVE</span></div><div class="job-mini"><span>👥 '+esc(j.vacancies??'—')+' Posts</span><span>📅 '+date(j.last_date)+'</span></div></div><div class="item-actions"><a class="btn home-details" href="'+detail+'">पूरी जानकारी →</a>'+apply+'</div></article>';
}
function social(){document.querySelectorAll('.social a').forEach(a=>{const t=(a.textContent||'').toLowerCase();let type=t.includes('telegram')?'tg':t.includes('instagram')?'ig':'wa';let label=t.includes('whatsapp')?(t.includes('channel')?'WhatsApp Channel':'WhatsApp Group'):type==='tg'?'Telegram':'Instagram';a.innerHTML=icons[type]+'<span>'+label+'</span>';a.classList.remove('wa','tg','ig');a.classList.add(type);});}
function css(){if(document.getElementById('yocewor-home-live-clean'))return;const s=document.createElement('style');s.id='yocewor-home-live-clean';s.textContent=`
.social a{display:inline-flex!important;align-items:center!important;justify-content:center!important;gap:6px!important;color:#fff!important;text-decoration:none!important;border-radius:9px!important;padding:7px 11px!important;font-weight:800!important}.social a svg{width:17px!important;height:17px!important;display:block!important}.social .wa{background:#0aa566!important}.social .tg{background:#168dcc!important}.social .ig{background:linear-gradient(135deg,#7b35ad,#e1306c,#f77737)!important}
#jobs .home-job{display:grid!important;grid-template-columns:minmax(0,1fr) auto!important;align-items:center!important;gap:8px!important;padding:8px 10px!important;min-height:56px!important}.home-job .item-title{font-size:12px!important;line-height:1.3!important}.home-job .job-mini{display:flex!important;gap:3px 12px!important;margin-top:3px!important;font-size:9px!important;color:#657d8e!important}.home-job .item-actions{display:flex!important;gap:5px!important;flex-wrap:nowrap!important;margin:0!important}.home-job .item-actions .btn{font-size:9px!important;padding:7px 9px!important;border-radius:7px!important;white-space:nowrap!important}.home-details{background:#087fbd!important;color:#fff!important}.home-apply{background:#07945f!important;color:#fff!important}.home-job a[href*="notification"],.home-job .orange{display:none!important}.home-job .new{background:#07945f!important;color:#fff!important;border-radius:9px!important;padding:2px 5px!important;font-size:7px!important}
@media(max-width:560px){.social a{padding:6px 8px!important;font-size:8px!important}.social a svg{width:15px!important;height:15px!important}#jobs .home-job{min-height:52px!important;padding:7px 8px!important;gap:5px!important}.home-job .item-title{font-size:10.5px!important}.home-job .job-mini{font-size:8px!important;gap:2px 7px!important}.home-job .item-actions .btn{font-size:8px!important;padding:6px 7px!important}}
`;document.head.appendChild(s)}
async function load(){try{const r=await fetch(U+'/rest/v1/jobs?select='+encodeURIComponent(F)+'&published=eq.true&order=updated_at.desc,created_at.desc&limit=1000',{headers:{apikey:K,Authorization:'Bearer '+K,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw Error(r.status);const all=await r.json();const jobs=all.filter(j=>!isAnswer(j));const active=jobs.filter(j=>!j.last_date||new Date(j.last_date+'T23:59:59')>=new Date()).slice(0,8);const show=active.length?active:jobs.slice(0,8);const box=document.getElementById('jobList');if(box)box.innerHTML=show.length?show.map(job).join(''):'<div class="empty">अभी कोई प्रकाशित भर्ती उपलब्ध नहीं है।</div>';const track=document.getElementById('tickerTrack');if(track){const x=jobs.slice(0,8).map(j=>'<span>🔥 '+esc(j.title)+' • Last Date: '+date(j.last_date)+'</span>').join(' &nbsp; • &nbsp; ');track.innerHTML=x+x;track.classList.add('live-scroll')}social();css()}catch(e){console.error('YOCEWOR home live:',e);social();css()}}
function init(){load();setInterval(load,20000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();