/* YOCEWOR live homepage layer — no images */
(function(){
'use strict';
const U='https://mzntgjyecymcpzciklfk.supabase.co',K='sb_publishable_AAXGC4EmiD4ELszpchz9Dw_Eryr6Usn';
const fields='id,title,type,department,start_date,last_date,vacancies,qualification,age,salary,description,apply_url,notification_url,created_at,updated_at,publish_date,published_at,published';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=d=>{if(!d)return'—';const a=String(d).split('-');return a.length===3?a[2]+'-'+a[1]+'-'+a[0]:esc(d)};
const norm=t=>String(t||'').toLowerCase().replace(/[-\s]+/g,'_');
function card(j){return '<article class="item"><div class="item-title">'+esc(j.title||'Government Recruitment')+' <span class="new">NEW</span></div><div class="meta">'+esc(j.department||'सरकारी विभाग')+(j.last_date?' • अंतिम तिथि: '+fmt(j.last_date):'')+(j.vacancies!=null?' • Vacancy: '+esc(j.vacancies):'')+'</div><div class="item-actions"><a class="btn" href="job-details.html?id='+encodeURIComponent(j.id)+'">पूरी जानकारी →</a>'+(j.apply_url?'<a class="btn green" href="'+esc(j.apply_url)+'" target="_blank" rel="noopener">Apply</a>':'')+(j.notification_url?'<a class="btn orange" href="'+esc(j.notification_url)+'" target="_blank" rel="noopener">Notification</a>':'')+'</div></article>'}
function ticker(items){const t=document.getElementById('tickerTrack');if(!t)return;const links=items.slice(0,8).map(j=>'<a href="job-details.html?id='+encodeURIComponent(j.id)+'">'+esc(j.title)+'</a>').join('');t.innerHTML=links||'<span>YOCEWOR पर नवीनतम अपडेट जल्द दिखाई देंगे।</span>';t.classList.remove('live-scroll');if(links){const copy=links; t.innerHTML=copy+copy;t.classList.add('live-scroll');}}
function stats(jobs){const hero=document.querySelector('.hero .chips');if(!hero)return;let box=document.getElementById('homeStats');if(!box){box=document.createElement('div');box.id='homeStats';box.className='hero-stats';hero.after(box)}box.innerHTML='<div class="hero-stat"><strong>'+jobs.length+'+</strong><span>Live Published Jobs</span></div><div class="hero-stat"><strong>24×7</strong><span>Latest Updates</span></div><div class="hero-stat"><strong><span class="live-dot"></span>LIVE</strong><span>Auto Refresh</span></div>'}
async function load(){try{const url=U+'/rest/v1/jobs?select='+encodeURIComponent(fields)+'&published=eq.true&order=updated_at.desc,created_at.desc&limit=1000';const r=await fetch(url,{headers:{apikey:K,Authorization:'Bearer '+K,Accept:'application/json'},cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);const all=await r.json();const jobs=all.filter(j=>norm(j.type)!=='answer_key');const active=jobs.filter(j=>!j.last_date||new Date(j.last_date+'T23:59:59')>=new Date()).slice(0,8);const shown=active.length?active:jobs.slice(0,8);const jl=document.getElementById('jobList');if(jl)jl.innerHTML=shown.length?shown.map(card).join(''):'<div class="empty">अभी कोई प्रकाशित भर्ती उपलब्ध नहीं है।</div>';const ul=document.getElementById('updateList');if(ul)ul.innerHTML=all.slice(0,5).map(card).join('')||'<div class="empty">अभी कोई update उपलब्ध नहीं है।</div>';ticker(all);stats(jobs);const st=document.querySelector('#jobs .section-head h3');if(st)st.innerHTML='💼 Latest Government Jobs <span class="live-status"><span class="live-dot"></span>LIVE</span>';}catch(e){console.error('YOCEWOR live home:',e)}}
function init(){load();setInterval(load,20000);const q=document.getElementById('searchInput');if(q)q.addEventListener('keydown',e=>{if(e.key==='Enter'&&typeof window.doSearch==='function')window.doSearch()});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
