(function(){
const U='https://mzntgjyecymcpzciklfk.supabase.co',K='sb_publishable_AAXGC4EmiD4ELszpchz9Dw_Eryr6Usn',F=U+'/functions/v1/team-management',SK=['sb-mzntgjyecymcpzciklfk-auth-token','yocewor_team_session'];
function p(){for(const k of SK){try{const x=JSON.parse(localStorage.getItem(k)||'null'),s=x?.currentSession||x?.session||x;if(s?.access_token)return{k,x,s}}catch(e){}}return null}
function save(p,s){try{let x=s;if(p.x?.currentSession)x={...p.x,currentSession:s};else if(p.x?.session)x={...p.x,session:s};localStorage.setItem(p.k,JSON.stringify(x))}catch(e){}}
async function refresh(){const p0=p();if(!p0?.s?.refresh_token)return null;try{const r=await fetch(U+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:K,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:p0.s.refresh_token})});if(!r.ok)return null;const s=await r.json();if(s.access_token){save(p0,s);return s}}catch(e){}return null}
async function request(action,extra={}){let q=p()?.s||await refresh();if(!q?.access_token)throw Error('Login session missing. Please login again.');async function call(s){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(F,{method:'POST',headers:{Authorization:'Bearer '+s.access_token,apikey:K,'Content-Type':'application/json'},body:JSON.stringify({action,...extra}),signal:c.signal});const txt=await r.text();let d={};try{d=JSON.parse(txt||'{}')}catch(e){throw Error('Invalid authentication service response.')}return{r,d}}finally{clearTimeout(t)}}let z=await call(q);if((z.r.status===401||z.r.status===403)&&q.refresh_token){const s=await refresh();if(s)z=await call(s)}if(!z.r.ok||z.d?.error)throw Error(z.d?.error||('Access verification failed (HTTP '+z.r.status+').'));return z.d}
async function requireRole(roles){const m=await request('me'),a=(Array.isArray(roles)?roles:[roles]).map(x=>String(x).toLowerCase());if(!a.includes(String(m.role||'').toLowerCase()))throw Error('You do not have permission to access this page.');return m}
async function signOut(){const s=p()?.s;try{if(s?.access_token)await fetch(U+'/auth/v1/logout',{method:'POST',headers:{Authorization:'Bearer '+s.access_token,apikey:K}})}catch(e){}SK.forEach(k=>localStorage.removeItem(k))}
window.YOCEWOR_AUTH={request,requireRole,readStoredSession:()=>p()?.s||null,SUPABASE_URL:U,SUPABASE_KEY:K,signOut};
function nav(){const h='<a href="/owner-dashboard.html">🏠 Home</a><a href="/dashboard.html">📊 Dashboard</a><a href="/team-management-live.html">👥 Team</a><a href="/content.html">📝 Content</a><a href="/edit-content.html">✏️ Edit Content</a><a href="/departments.html">🏢 Departments</a><a href="/important-notice.html">📢 Important Notice</a><a href="/live-notice.html">🔴 Live Notice</a><a href="/settings.html">⚙️ Settings</a><a href="/activity-audit.html">🧾 Activity / Audit</a><a href="/" id="yocewor-nav-logout">🚪 Logout</a>';document.querySelectorAll('.nav').forEach(n=>{n.innerHTML=h;const cur=location.pathname.replace(/\/$/,'')||'/owner-dashboard.html';n.querySelectorAll('a').forEach(a=>{if(a.getAttribute('href')===cur)a.classList.add('active')});n.querySelector('#yocewor-nav-logout')?.addEventListener('click',async e=>{e.preventDefault();await signOut();location.href='/'})})}
if(document.readyState==='loading')addEventListener('DOMContentLoaded',nav);else nav();
})();