(function(){'use strict';
const URL='https://mzntgjyecymcpzciklfk.supabase.co',KEY='sb_publishable_AAXGC4EmiD4ELszpchz9Dw_Eryr6Usn';
const S=window.supabase?.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true}}); if(!S)return;
const esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
let me=null,profiles={};
function avatar(p,size=62){const u=p?.avatar_url;return u?'<img src="'+esc(u)+'" alt="">':'<span>'+esc((p?.display_name||p?.username||'U').slice(0,1).toUpperCase())+'</span>'}
function css(){if(document.getElementById('yocewor-story-fix-css'))return;const s=document.createElement('style');s.id='yocewor-story-fix-css';s.textContent=`
.yw-stories{display:flex;gap:14px;overflow-x:auto;padding:12px 10px 14px;margin:0 0 16px;scrollbar-width:none;background:transparent}
.yw-stories::-webkit-scrollbar{display:none}.yw-story{width:74px;min-width:74px;text-align:center;color:#a7acc1;font-size:11px;position:relative}.yw-story button{display:block;border:0;background:transparent;color:inherit;width:74px;padding:0;margin:0;cursor:pointer}.yw-avatar{width:66px;height:66px;margin:0 auto 6px;border-radius:50%;padding:3px;background:linear-gradient(135deg,#ff6a00,#ff2f7e,#7c4dff);position:relative}.yw-avatar-inner{width:100%;height:100%;border-radius:50%;border:3px solid #101323;background:#1b2030;display:grid;place-items:center;overflow:hidden;color:#fff;font-size:23px;font-weight:900}.yw-avatar-inner img{width:100%;height:100%;object-fit:cover}.yw-story.no-story .yw-avatar{padding:0;background:none}.yw-story.no-story .yw-avatar-inner{border:1px solid #30364f}.yw-plus{position:absolute;right:1px;bottom:2px;width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:#1688ff;color:#fff;border:2px solid #08090c;font-size:17px;font-weight:900;line-height:1}.yw-story-name{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.yw-viewer{position:fixed;inset:0;z-index:10000;background:#000;display:grid;place-items:center}.yw-viewer-box{width:min(520px,100vw);height:min(900px,100vh);position:relative;background:#090b12;overflow:hidden}.yw-viewer-media{width:100%;height:100%;object-fit:contain;background:#000}.yw-viewer-top{position:absolute;left:14px;right:14px;top:14px;z-index:2;display:flex;align-items:center;gap:9px}.yw-viewer-user{display:flex;align-items:center;gap:8px;flex:1;background:#0006;border-radius:20px;padding:6px 10px;color:#fff}.yw-viewer-user img,.yw-viewer-user .yw-vmini{width:34px;height:34px;border-radius:50%;object-fit:cover;background:#333;display:grid;place-items:center}.yw-viewer-close{width:40px;height:40px;border:0;border-radius:50%;background:#0008;color:#fff;font-size:27px}.yw-viewer-caption{position:absolute;left:14px;right:14px;bottom:18px;color:#fff;background:#0008;padding:12px;border-radius:14px}.yw-add-input{display:none}`;document.head.appendChild(s)}
async function session(){const r=await S.auth.getSession();me=r.data.session?.user||null;return me}
async function load(){if(!me)return;const [own,fol]=await Promise.all([S.from('stories').select('*').eq('user_id',me.id).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false}),S.from('follows').select('following_id').eq('follower_id',me.id).eq('status','accepted')]);
let ids=[me.id,...(fol.data||[]).map(x=>x.following_id).filter(Boolean)];ids=[...new Set(ids)];let stories=[];if(ids.length){const r=await S.from('stories').select('*').in('user_id',ids).gt('expires_at',new Date().toISOString()).order('created_at',{ascending:false});stories=r.data||[]}
const latest={};stories.forEach(x=>{if(!latest[x.user_id])latest[x.user_id]=x});const pids=ids;const pr=await S.from('profiles').select('id,display_name,username,avatar_url,is_verified').in('id',pids);profiles={};(pr.data||[]).forEach(p=>profiles[p.id]=p);
render(latest,ids.filter(id=>id!==me.id&&latest[id]));
}
function render(latest,followingWithStories){const old=document.querySelector('.stories');if(!old)return;const box=document.createElement('div');box.className='yw-stories';box.dataset.ywStories='1';
const own=profiles[me.id]||{};const ownStory=latest[me.id];box.appendChild(card(own,ownStory,true));followingWithStories.forEach(id=>box.appendChild(card(profiles[id]||{},latest[id],false)));
old.replaceWith(box);const composer=document.querySelector('.composer');if(composer)composer.remove();
}
function card(p,story,isOwn){const wrap=document.createElement('div');wrap.className='yw-story'+(story?'':' no-story');const b=document.createElement('button');b.type='button';b.setAttribute('aria-label',isOwn?'Your story':('@'+(p.username||'user')+' story'));b.innerHTML='<div class="yw-avatar"><div class="yw-avatar-inner">'+avatar(p)+'</div>'+(isOwn&&!story?'<span class="yw-plus">+</span>':'')+'</div><div class="yw-story-name">'+(isOwn?'Your story':esc(p.username||p.display_name||'user'))+'</div>';b.onclick=()=>story?viewStory(story,p):openPicker();wrap.appendChild(b);if(isOwn&&!story){wrap.onclick=e=>{if(e.target.closest('button'))return;openPicker()}}return wrap}
function picker(){let i=document.getElementById('yw-story-input');if(i)return i;i=document.createElement('input');i.id='yw-story-input';i.className='yw-add-input';i.type='file';i.accept='image/*,video/*';document.body.appendChild(i);i.onchange=()=>{const f=i.files?.[0];if(f)createStory(f);i.value=''};return i}
function openPicker(){picker().click()}
async function createStory(file){try{const path=me.id+'/stories/'+Date.now()+'-'+file.name.replace(/[^a-zA-Z0-9._-]/g,'');const up=await S.storage.from('yocewor-media').upload(path,file,{upsert:false,cacheControl:'3600'});if(up.error)throw up.error;const url=S.storage.from('yocewor-media').getPublicUrl(path).data.publicUrl;const type=file.type.startsWith('video/')?'video':'image';const r=await S.from('stories').insert({user_id:me.id,media_url:url,media_type:type,caption:'',visibility:'public',expires_at:new Date(Date.now()+86400000).toISOString()});if(r.error)throw r.error;await load();if(window.toast)toast('Story added');else alert('Story added')}catch(e){if(window.toast)toast(e.message||'Could not add story');else alert(e.message||'Could not add story')}}
function viewStory(story,p){const m=document.createElement('div');m.className='yw-viewer';const media=story.media_type==='video'?'<video class="yw-viewer-media" src="'+esc(story.media_url)+'" autoplay controls playsinline></video>':'<img class="yw-viewer-media" src="'+esc(story.media_url)+'" alt="Story">';const avh=p.avatar_url?'<img src="'+esc(p.avatar_url)+'">':'<span class="yw-vmini">'+esc((p.display_name||p.username||'U').slice(0,1).toUpperCase())+'</span>';m.innerHTML='<div class="yw-viewer-box">'+media+'<div class="yw-viewer-top"><div class="yw-viewer-user">'+avh+'<b>'+esc(p.username||p.display_name||'user')+'</b></div><button class="yw-viewer-close">×</button></div>'+(story.caption?'<div class="yw-viewer-caption">'+esc(story.caption)+'</div>':'')+'</div>';m.querySelector('.yw-viewer-close').onclick=()=>m.remove();m.addEventListener('click',e=>{if(e.target===m)m.remove()});document.body.appendChild(m);S.from('story_views').upsert({story_id:story.id,viewer_id:me.id},{onConflict:'story_id,viewer_id'}).catch(()=>{})}
function watch(){const target=document.getElementById('root')||document.body;const mo=new MutationObserver(()=>{const s=document.querySelector('.stories');if(s&&!s.dataset.ywPatched){s.dataset.ywPatched='1';load()}});mo.observe(target,{childList:true,subtree:true});setTimeout(load,700);setInterval(()=>{if(document.querySelector('.yw-stories'))load()},30000)}
css();session().then(()=>watch());
})();