(()=>{
'use strict';
const D=document;
const icon=(name)=>{const p={home:'M3 10.5 12 3l9 7.5M5.5 9v11h13V9M9 20v-6h6v6',search:'m20 20-4.3-4.3M10.8 17a6.2 6.2 0 1 1 0-12.4 6.2 6.2 0 0 1 0 12.4',reels:'M4 4h16v16H4zM4 9h16M9 4l4 5M15 4l4 5',plus:'M12 5v14M5 12h14',heart:'M20.8 8.8c0 5-8.8 10.2-8.8 10.2S3.2 13.8 3.2 8.8A4.8 4.8 0 0 1 12 6.2a4.8 4.8 0 0 1 8.8 2.6Z',user:'M20 21a8 8 0 0 0-16 0M12 13a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',settings:'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7ZM19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-2.5V20a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1A1.7 1.7 0 0 0 8 15a1.7 1.7 0 0 0-1.6-1H6v-2.5h.4A1.7 1.7 0 0 0 8 10a1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6v-.2h2.5V5a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v2.5H21a1.7 1.7 0 0 0-1.6 1.5Z'}[name]||'';return `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${p}"/></svg>`};
const css=`
:root{--yo-bg:#07070b;--yo-panel:#101116;--yo-line:#24262e;--yo-text:#f5f5f7;--yo-muted:#9b9ca4;--yo-accent:#0095f6}
body.yo-polished{background:var(--yo-bg)!important;color:var(--yo-text)!important}
body.yo-polished .top{height:62px!important;background:rgba(7,7,11,.88)!important;border-bottom:1px solid var(--yo-line)!important;backdrop-filter:blur(22px)!important}
body.yo-polished .topin{max-width:1180px!important}
body.yo-polished .bottom{display:none!important}
body.yo-polished .wrap{max-width:1180px!important}
body.yo-polished .card{background:var(--yo-panel)!important;border-color:var(--yo-line)!important;box-shadow:0 10px 35px rgba(0,0,0,.22)!important}
body.yo-polished .post{border-radius:16px!important}
body.yo-polished .posthead{padding:14px 4px!important}
body.yo-polished .posttext{padding:0 4px 12px!important}
body.yo-polished .postactions{padding:5px 0!important}
body.yo-polished .action{font-size:13px!important}
body.yo-polished .splash{z-index:1000}
.yo-top-actions{display:flex;align-items:center;gap:8px}
.yo-icon-btn{width:40px;height:40px;border:0;background:transparent;color:#f5f5f7;border-radius:50%;display:grid;place-items:center}
.yo-icon-btn:hover{background:#17181d}.yo-icon-btn svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
.yo-nav{position:fixed;left:50%;bottom:10px;transform:translateX(-50%);width:min(640px,calc(100% - 20px));height:64px;z-index:500;background:rgba(16,17,22,.94);border:1px solid #292b34;border-radius:22px;display:flex;align-items:center;justify-content:space-around;padding:4px 8px;box-shadow:0 15px 45px rgba(0,0,0,.45);backdrop-filter:blur(22px)}
.yo-nav button{flex:1;height:54px;border:0;background:transparent;color:#9b9ca4;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:3px;font-size:10px;font-weight:750}.yo-nav button.active{color:#fff}.yo-nav svg{width:23px;height:23px;fill:none;stroke:currentColor;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}.yo-create{width:46px!important;max-width:46px!important;flex:none!important;border:1px solid #4a4b53!important;border-radius:15px!important;color:#fff!important}.yo-create svg{width:24px;height:24px}
.yo-settings{position:fixed;inset:0;z-index:900;background:rgba(0,0,0,.62);display:none;align-items:flex-end;justify-content:center;backdrop-filter:blur(8px)}.yo-settings.open{display:flex}.yo-sheet{width:min(620px,100%);max-height:88vh;overflow:auto;background:#15161b;border:1px solid #30323a;border-bottom:0;border-radius:26px 26px 0 0;padding:14px 18px 28px;box-shadow:0 -20px 70px rgba(0,0,0,.45)}.yo-sheet-handle{width:42px;height:4px;border-radius:9px;background:#555861;margin:0 auto 16px}.yo-sheet h2{margin:4px 0 18px;font-size:23px}.yo-setting{display:flex;align-items:center;gap:14px;padding:15px 4px;border-bottom:1px solid #292b32}.yo-setting .sicon{width:40px;height:40px;border-radius:12px;background:#22242b;display:grid;place-items:center}.yo-setting .sicon svg{width:21px;height:21px;fill:none;stroke:#fff;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.yo-setting .stext{flex:1}.yo-setting strong{display:block;font-size:14px}.yo-setting small{display:block;color:#9698a1;margin-top:3px}.yo-switch{width:48px;height:28px;border:0;border-radius:20px;background:#3a3c44;padding:3px}.yo-switch i{display:block;width:22px;height:22px;border-radius:50%;background:#fff;transition:.2s}.yo-switch.on{background:#0095f6}.yo-switch.on i{transform:translateX(20px)}
/* Distinct Meta-style verification badge: scalloped blue seal, not a plain circle. */
.yo-verified{display:inline-grid!important;place-items:center!important;width:19px!important;height:19px!important;margin-left:5px!important;vertical-align:-4px!important;background:#0095f6!important;clip-path:polygon(50% 0%,60% 5%,71% 3%,79% 11%,89% 13%,92% 24%,99% 32%,95% 43%,100% 53%,94% 62%,95% 73%,85% 80%,81% 91%,70% 90%,60% 98%,50% 94%,40% 98%,30% 90%,19% 91%,15% 80%,5% 73%,6% 62%,0 53%,5% 43%,1% 32%,8% 24%,11% 13%,21% 11%,29% 3%,40% 5%);box-shadow:none!important;color:#fff!important;font-size:0!important}.yo-verified:after{content:'✓';font-size:12px;font-weight:1000;line-height:1;color:#fff}
.yo-reels-mode #root{max-width:760px;margin:auto}.yo-reels-mode .reel{height:calc(100vh - 84px)!important;min-height:520px!important;margin:0 0 12px!important;border-radius:18px!important;scroll-snap-align:start!important}.yo-reels-mode .reel img,.yo-reels-mode .reel video{height:100%!important;max-height:none!important;object-fit:cover!important}.yo-reels-mode #root{scroll-snap-type:y mandatory}.yo-reels-mode .app{padding-top:8px!important}
@media(max-width:700px){.yo-nav{bottom:7px;height:60px;border-radius:20px}.yo-nav button{height:52px}.yo-settings{align-items:flex-end}.yo-sheet{border-radius:24px 24px 0 0}.yo-reels-mode .reel{height:calc(100vh - 78px)!important;border-radius:0!important;margin-left:-7px!important;margin-right:-7px!important}}
`;
function inject(){
 if(D.getElementById('yo-polish-style'))return;
 const s=D.createElement('style');s.id='yo-polish-style';s.textContent=css;D.head.appendChild(s);D.body.classList.add('yo-polished');
 const top=D.querySelector('#topActions');
 if(top){top.innerHTML='';const b=D.createElement('button');b.className='yo-icon-btn';b.title='Settings';b.innerHTML=icon('settings');b.onclick=openSettings;top.appendChild(b)}
 buildNav();buildSettings();makeVerified();wireReels();
}
function clickByText(re){const els=[...D.querySelectorAll('button,a,[role=button]')];const x=els.find(e=>re.test((e.textContent||'').trim()));if(x){x.click();return true}return false}
function navAction(key){
 const map={home:/^Home$|^होम$/i,explore:/^Explore$|^एक्सप्लोर$/i,reels:/^Reels$|^रील्स$/i,profile:/^Profile$|^प्रोफाइल$/i};
 if(key==='create'){return clickByText(/^Create$|^Create post$|^पोस्ट बनाएं$/i)}
 return clickByText(map[key]||/nomatch/);
}
function buildNav(){if(D.getElementById('yo-nav'))return;const n=D.createElement('nav');n.id='yo-nav';n.className='yo-nav';[['home','Home','home'],['explore','Explore','search'],['reels','Reels','reels'],['create','Create','plus'],['profile','Profile','user']].forEach(([k,l,i])=>{const b=D.createElement('button');b.dataset.key=k;b.innerHTML=icon(i)+`<span>${l}</span>`;b.onclick=()=>{if(k==='reels'){D.body.classList.add('yo-reels-mode')}else{D.body.classList.remove('yo-reels-mode')}navAction(k);setActive(k)};n.appendChild(b)});D.body.appendChild(n);setActive('home')}
function setActive(k){document.querySelectorAll('.yo-nav button').forEach(b=>b.classList.toggle('active',b.dataset.key===k))}
function buildSettings(){if(D.getElementById('yo-settings'))return;const o=D.createElement('div');o.id='yo-settings';o.className='yo-settings';o.innerHTML=`<div class="yo-sheet"><div class="yo-sheet-handle"></div><h2>Settings & privacy</h2><div class="yo-setting"><div class="sicon">${icon('settings')}</div><div class="stext"><strong>Settings</strong><small>Account, notifications and preferences</small></div></div><div class="yo-setting"><div class="sicon">${icon('heart')}</div><div class="stext"><strong>Notifications</strong><small>Likes, comments and new followers</small></div><button class="yo-switch on" data-pref="notifications"><i></i></button></div><div class="yo-setting"><div class="sicon">${icon('user')}</div><div class="stext"><strong>Private account</strong><small>Only approved followers can see your posts</small></div><button class="yo-switch" data-pref="private"><i></i></button></div><div class="yo-setting"><div class="sicon">${icon('settings')}</div><div class="stext"><strong>Dark appearance</strong><small>Use YOCEWOR's dark visual system</small></div><button class="yo-switch on" data-pref="dark"><i></i></button></div><div class="yo-setting"><div class="sicon">?</div><div class="stext"><strong>Help Center</strong><small>Report a problem or get support</small></div><button class="yo-icon-btn" onclick="alert('YOCEWOR Help Center coming from your support system.')">›</button></div><div class="yo-setting"><div class="sicon">🔒</div><div class="stext"><strong>Privacy & security</strong><small>Blocked accounts, login activity and security</small></div><button class="yo-icon-btn" onclick="alert('Privacy & security controls are available here.')">›</button></div><button id="yo-close-settings" class="yo-icon-btn" style="margin:14px auto 0;width:100%;height:46px;border-radius:14px;background:#24262d">Close</button></div>`;D.body.appendChild(o);o.onclick=e=>{if(e.target===o)o.classList.remove('open')};D.getElementById('yo-close-settings').onclick=()=>o.classList.remove('open');o.querySelectorAll('.yo-switch').forEach(b=>b.onclick=()=>b.classList.toggle('on'))}
function openSettings(){D.getElementById('yo-settings')?.classList.add('open')}
function makeVerified(){D.querySelectorAll('.verify').forEach(e=>{e.classList.remove('verify');e.classList.add('yo-verified')});D.querySelectorAll('[title="Verified"],[aria-label="Verified"]').forEach(e=>e.classList.add('yo-verified'))}
function wireReels(){const watch=()=>{makeVerified();if(D.body.classList.contains('yo-reels-mode')){D.querySelectorAll('.reel video').forEach(v=>{v.setAttribute('playsinline','');v.muted=true;const r=new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){v.play().catch(()=>{});x.target.closest('.reel')?.scrollIntoView({block:'nearest'})}else v.pause()}),{threshold:.72});r.observe(v)}}};watch();setTimeout(watch,1200)}
new MutationObserver(()=>{makeVerified()}).observe(D.body,{subtree:true,childList:true});
window.YOCEWOR_POLISH={inject,openSettings};
})();